version: "3.8"
services:
    isamples_modelserver:
        build:
            context: .
        ports:
            - "9000:9000"
        volumes:
            - metadata_models:/app/metadata_models

volumes:
    metadata_models:
        name: metadata_models
        external: true